from analise_exploratoria.abas.ian import renderizar_ian
from analise_exploratoria.abas.iaa import renderizar_iaa
from analise_exploratoria.abas.ida import renderizar_ida
from analise_exploratoria.abas.ieg import renderizar_ieg
from analise_exploratoria.abas.inde import renderizar_inde
from analise_exploratoria.abas.ipp import renderizar_ipp
from analise_exploratoria.abas.ips import renderizar_ips
from analise_exploratoria.abas.ipv import renderizar_ipv
from analise_exploratoria.abas.panorama import renderizar_panorama
